import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";

import Image from "next/image";
import pic from "/public/pic2.png";
import Footer from "./components/footer";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Food Lovers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

          {/* WORK starts from here. Its a orange div. Main heading & logo */}
          
          <div className="bg-orange-400 w-full h-[100px]">
            <div className="flex w-full">

               <div>
              <Image src={pic} alt="logo" width={150} height={150}></Image> </div>
       
               <div className="flex pt-[30px] w-full">
               <h1 className="flex ml-[35%] text-emerald-600 font-bold text-4xl">Food Lovers</h1> </div>
               </div>
              </div>  
              <Navbar/>


        {children}
        <Footer/>
    
      </body>
    </html>
  );
}
